/// Backend-shaped response used only by [SmokeApiClient] in local preview.
///
/// UI widgets never import this fixture; they consume it through the same
/// `/api/reports` and `/api/reports/{report_id}` boundary as production.
const smokeReportDetail = <String, dynamic>{
  'report_id': 'smoke-report',
  'status': 'succeeded',
  'generated_at': '2026-08-28T08:30:00Z',
  'snapshot_hash': 'smoke-snapshot',
  'source_digest': 'smoke-source',
  'has_updates': false,
  'reused': false,
  'missing_sections': <String>[],
  'snapshot': {
    'summary': {
      'profile': {'nickname': '林晓晴', 'height_cm': 162.0, 'weight_kg': 67.5},
      'patient_note_text': '近 3 个月月经周期不规律，最近间隔达 51 天。',
      'disclaimers': ['仅供参考，不构成诊断或治疗建议'],
      'current_medications': <Map<String, dynamic>>[],
      'cycle_summary': {
        'count': 5,
        'range_start': '2025-09-13',
        'range_end': '2026-08-28',
      },
      'weight_summary': {
        'count': 5,
        'latest_weight_kg': 67.5,
        'latest_bmi': 25.7,
        'bmi_reference_lower': 18.5,
        'bmi_reference_upper': 24.0,
        'bmi_status': 'high',
      },
    },
    'trends': {
      'labs': [
        {
          'metric_id': 'glucose',
          'metric_name': '空腹血糖',
          'unit': 'mmol/L',
          'comparability': 'comparable',
          'display_mode': 'trend',
          'points': [
            {
              'original_item_name': '空腹血糖',
              'date': '2024-08-13',
              'raw_value': '5.8',
              'numeric_value': 5.8,
              'original_unit': 'mmol/L',
              'normalized_value': 5.8,
              'normalized_unit': 'mmol/L',
              'normalized_reference_lower': 3.9,
              'normalized_reference_upper': 5.5,
              'abnormal_status': 'high',
              'comparability': 'comparable',
              'source_number': 1,
              'facility': '医院 A',
            },
            {
              'original_item_name': '空腹血糖',
              'date': '2025-04-12',
              'raw_value': '5.2',
              'numeric_value': 5.2,
              'original_unit': 'mmol/L',
              'normalized_value': 5.2,
              'normalized_unit': 'mmol/L',
              'normalized_reference_lower': 3.9,
              'normalized_reference_upper': 5.5,
              'abnormal_status': 'normal',
              'comparability': 'comparable',
              'source_number': 2,
              'facility': '医院 A',
            },
            {
              'original_item_name': '空腹血糖',
              'date': '2025-12-01',
              'raw_value': '92',
              'numeric_value': 92,
              'original_unit': 'mg/dL',
              'normalized_value': 5.1,
              'normalized_unit': 'mmol/L',
              'normalized_reference_lower': 4.1,
              'normalized_reference_upper': 5.9,
              'abnormal_status': 'normal',
              'comparability': 'comparable',
              'source_number': 3,
              'facility': '医院 C',
            },
            {
              'original_item_name': '空腹血糖',
              'date': '2026-03-06',
              'raw_value': '5.4',
              'numeric_value': 5.4,
              'original_unit': 'mmol/L',
              'normalized_value': 5.4,
              'normalized_unit': 'mmol/L',
              'abnormal_status': 'unknown',
              'comparability': 'incomparable',
              'exclusion_reason': 'reference_range_missing',
              'source_number': 4,
              'facility': '医院 C',
            },
            {
              'original_item_name': '空腹血糖',
              'date': '2026-06-20',
              'raw_value': '5.3',
              'numeric_value': 5.3,
              'original_unit': 'mmol/L',
              'normalized_value': 5.3,
              'normalized_unit': 'mmol/L',
              'normalized_reference_lower': 3.9,
              'normalized_reference_upper': 5.7,
              'abnormal_status': 'normal',
              'comparability': 'comparable',
              'source_number': 5,
              'facility': '医院 A',
            },
            {
              'original_item_name': '空腹血糖',
              'date': '2026-08-25',
              'raw_value': '5.6',
              'numeric_value': 5.6,
              'original_unit': 'mmol/L',
              'normalized_value': 5.6,
              'normalized_unit': 'mmol/L',
              'normalized_reference_lower': 3.9,
              'normalized_reference_upper': 6.1,
              'abnormal_status': 'normal',
              'comparability': 'comparable',
              'source_number': 6,
              'facility': '医院 B',
            },
          ],
        },
        {
          'metric_id': 'hba1c',
          'metric_name': 'HbA1c',
          'unit': '%',
          'points': [
            {
              'original_item_name': 'HbA1c',
              'date': '2026-08-25',
              'raw_value': '5.5',
              'original_unit': '%',
              'abnormal_status': 'normal',
            },
          ],
        },
        {
          'metric_id': 'total_testosterone',
          'metric_name': '总睾酮',
          'unit': 'nmol/L',
          'comparability': 'caution',
          'comparability_reason': 'hormone_context_incomplete',
          'display_mode': 'single_result',
          'points': [
            {
              'original_item_name': '总睾酮',
              'date': '2026-08-24',
              'raw_value': '90',
              'numeric_value': 90,
              'original_unit': 'ng/dL',
              'normalized_value': 3.123,
              'normalized_unit': 'nmol/L',
              'normalized_reference_lower': 0.3,
              'normalized_reference_upper': 2.6,
              'abnormal_status': 'high',
              'comparability': 'comparable',
              'source_number': 7,
            },
          ],
        },
        {
          'metric_id': 'triglyceride',
          'metric_name': '甘油三酯',
          'unit': 'mmol/L',
          'points': [
            {
              'original_item_name': '甘油三酯',
              'date': '2026-06-20',
              'raw_value': '1.4',
              'original_unit': 'mmol/L',
              'abnormal_status': 'normal',
            },
          ],
        },
      ],
      'weights': [
        {'record_date': '2026-08-02', 'weight_kg': 68.5, 'bmi': 26.1},
        {'record_date': '2026-08-08', 'weight_kg': 67.2, 'bmi': 25.6},
        {'record_date': '2026-08-15', 'weight_kg': 66.5, 'bmi': 25.3},
        {'record_date': '2026-08-22', 'weight_kg': 67.3, 'bmi': 25.6},
        {
          'record_date': '2026-08-28',
          'weight_kg': 67.5,
          'bmi': 25.7,
          'bmi_reference_lower': 18.5,
          'bmi_reference_upper': 24.0,
          'bmi_status': 'high',
        },
      ],
      'cycles': [
        {
          'start_date': '2025-09-13',
          'end_date': '2025-09-17',
          'cycle_end_date': '2025-11-24',
          'cycle_length_days': 73,
          'duration_days': 5,
        },
        {
          'start_date': '2025-11-25',
          'end_date': '2025-11-28',
          'cycle_end_date': '2026-02-18',
          'cycle_length_days': 86,
          'duration_days': 4,
        },
        {
          'start_date': '2026-02-19',
          'end_date': '2026-02-25',
          'cycle_end_date': '2026-04-11',
          'cycle_length_days': 52,
          'duration_days': 7,
        },
        {
          'start_date': '2026-04-12',
          'end_date': '2026-04-17',
          'cycle_end_date': '2026-07-04',
          'cycle_length_days': 84,
          'duration_days': 6,
        },
        {
          'start_date': '2026-07-05',
          'end_date': '2026-07-08',
          'cycle_end_date': null,
          'cycle_length_days': null,
          'duration_days': 4,
        },
      ],
    },
    'records': <String, dynamic>{},
    'sources': <Map<String, dynamic>>[],
  },
  'date_sources': <String, dynamic>{},
  'data_freshness': <String, dynamic>{},
};

const smokeReportListItem = <String, dynamic>{
  'report_id': 'smoke-report',
  'status': 'succeeded',
  'generated_at': '2026-08-28T08:30:00Z',
  'snapshot_hash': 'smoke-snapshot',
  'source_digest': 'smoke-source',
  'has_updates': false,
  'reused': false,
  'missing_sections': <String>[],
};
