"""create clinical text records

Revision ID: 20260827_0030
Revises: 20260827_0029
Create Date: 2026-08-27 21:14:54.772143
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import pomi_backend.db.types

revision: str = "20260827_0030"
down_revision: str | None = "20260827_0029"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "imaging_report",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("document_revision_id", sa.String(length=36), nullable=False),
        sa.Column("ocr_result_id", sa.String(length=36), nullable=False),
        sa.Column("facility", sa.String(length=200), nullable=True),
        sa.Column("examination_name", sa.String(length=200), nullable=True),
        sa.Column("body_part", sa.String(length=200), nullable=True),
        sa.Column("modality", sa.String(length=100), nullable=True),
        sa.Column("examination_date", sa.Date(), nullable=True),
        sa.Column("report_date", sa.Date(), nullable=True),
        sa.Column("findings_text", sa.Text(), nullable=False),
        sa.Column("conclusion_text", sa.Text(), nullable=False),
        sa.Column("confirmed_payload", sa.JSON(), nullable=False),
        sa.Column("confirmed_by_uid", sa.String(length=36), nullable=False),
        sa.Column("confirmed_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["confirmed_by_uid"],
            ["user_account.uid"],
            name=op.f("fk_imaging_report_confirmed_by_uid_user_account"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.id"],
            name=op.f("fk_imaging_report_document_id_document"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["document_revision_id"],
            ["document_revision.id"],
            name=op.f("fk_imaging_report_document_revision_id_document_revision"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["ocr_result_id"],
            ["ocr_result.id"],
            name=op.f("fk_imaging_report_ocr_result_id_ocr_result"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient_profile.patient_id"],
            name=op.f("fk_imaging_report_patient_id_patient_profile"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_imaging_report")),
        sa.UniqueConstraint("ocr_result_id", name="uq_imaging_report_ocr_result"),
    )
    with op.batch_alter_table("imaging_report", schema=None) as batch_op:
        batch_op.create_index(
            "ix_imaging_report_patient_examined", ["patient_id", "examination_date"], unique=False
        )

    op.create_table(
        "outpatient_record",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("document_revision_id", sa.String(length=36), nullable=False),
        sa.Column("ocr_result_id", sa.String(length=36), nullable=False),
        sa.Column("facility", sa.String(length=200), nullable=True),
        sa.Column("department", sa.String(length=200), nullable=True),
        sa.Column("doctor_name", sa.String(length=100), nullable=True),
        sa.Column("visit_date", sa.Date(), nullable=False),
        sa.Column("chief_complaint", sa.Text(), nullable=True),
        sa.Column("diagnosis_summary", sa.Text(), nullable=False),
        sa.Column("treatment_plan", sa.Text(), nullable=True),
        sa.Column("medical_advice", sa.Text(), nullable=False),
        sa.Column("confirmed_payload", sa.JSON(), nullable=False),
        sa.Column("confirmed_by_uid", sa.String(length=36), nullable=False),
        sa.Column("confirmed_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["confirmed_by_uid"],
            ["user_account.uid"],
            name=op.f("fk_outpatient_record_confirmed_by_uid_user_account"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.id"],
            name=op.f("fk_outpatient_record_document_id_document"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["document_revision_id"],
            ["document_revision.id"],
            name=op.f("fk_outpatient_record_document_revision_id_document_revision"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["ocr_result_id"],
            ["ocr_result.id"],
            name=op.f("fk_outpatient_record_ocr_result_id_ocr_result"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient_profile.patient_id"],
            name=op.f("fk_outpatient_record_patient_id_patient_profile"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outpatient_record")),
        sa.UniqueConstraint("ocr_result_id", name="uq_outpatient_record_ocr_result"),
    )
    with op.batch_alter_table("outpatient_record", schema=None) as batch_op:
        batch_op.create_index(
            "ix_outpatient_record_patient_visit", ["patient_id", "visit_date"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("outpatient_record", schema=None) as batch_op:
        batch_op.drop_index("ix_outpatient_record_patient_visit")

    op.drop_table("outpatient_record")
    with op.batch_alter_table("imaging_report", schema=None) as batch_op:
        batch_op.drop_index("ix_imaging_report_patient_examined")

    op.drop_table("imaging_report")
    # ### end Alembic commands ###
