"""create report foundation

Revision ID: 20260827_0027
Revises: 20260827_0020
Create Date: 2026-08-27 20:57:45.784029
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import pomi_backend.db.types

revision: str = "20260827_0027"
down_revision: str | None = "20260827_0020"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "patient_note",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("visit_context", sa.String(length=200), nullable=True),
        sa.Column("original_text", sa.Text(), nullable=False),
        sa.Column("confirmed_text", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("confirmed_by_uid", sa.String(length=36), nullable=True),
        sa.Column("confirmed_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("source_note_id", sa.String(length=36), nullable=True),
        sa.Column("consumed_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("created_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('draft', 'confirmed', 'skipped', 'consumed')",
            name=op.f("ck_patient_note_patient_note_status"),
        ),
        sa.ForeignKeyConstraint(
            ["confirmed_by_uid"],
            ["user_account.uid"],
            name=op.f("fk_patient_note_confirmed_by_uid_user_account"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient_profile.patient_id"],
            name=op.f("fk_patient_note_patient_id_patient_profile"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_note_id"],
            ["patient_note.id"],
            name=op.f("fk_patient_note_source_note_id_patient_note"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_patient_note")),
    )
    with op.batch_alter_table("patient_note", schema=None) as batch_op:
        batch_op.create_index(
            "ix_patient_note_patient_created", ["patient_id", "created_at"], unique=False
        )

    op.create_table(
        "report_snapshot",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("patient_note_id", sa.String(length=36), nullable=True),
        sa.Column("previous_report_id", sa.String(length=36), nullable=True),
        sa.Column("report_status", sa.String(length=16), nullable=False),
        sa.Column("snapshot_json", sa.JSON(), nullable=True),
        sa.Column("date_source_json", sa.JSON(), nullable=True),
        sa.Column("freshness_result_json", sa.JSON(), nullable=True),
        sa.Column("source_digest", sa.String(length=64), nullable=False),
        sa.Column("snapshot_hash", sa.String(length=64), nullable=True),
        sa.Column("generated_by_uid", sa.String(length=36), nullable=False),
        sa.Column(
            "report_generated_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=True
        ),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("created_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "report_status IN ('pending', 'succeeded', 'failed')",
            name=op.f("ck_report_snapshot_report_snapshot_status"),
        ),
        sa.CheckConstraint(
            "report_status != 'succeeded' OR "
            "(snapshot_json IS NOT NULL AND snapshot_hash IS NOT NULL "
            "AND report_generated_at IS NOT NULL)",
            name=op.f("ck_report_snapshot_successful_report_complete"),
        ),
        sa.ForeignKeyConstraint(
            ["generated_by_uid"],
            ["user_account.uid"],
            name=op.f("fk_report_snapshot_generated_by_uid_user_account"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient_profile.patient_id"],
            name=op.f("fk_report_snapshot_patient_id_patient_profile"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["patient_note_id"],
            ["patient_note.id"],
            name=op.f("fk_report_snapshot_patient_note_id_patient_note"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["previous_report_id"],
            ["report_snapshot.id"],
            name=op.f("fk_report_snapshot_previous_report_id_report_snapshot"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_snapshot")),
        sa.UniqueConstraint("patient_id", "source_digest", name="uq_report_patient_source_digest"),
    )
    with op.batch_alter_table("report_snapshot", schema=None) as batch_op:
        batch_op.create_index(
            "ix_report_snapshot_patient_generated",
            ["patient_id", "report_generated_at"],
            unique=False,
        )

    op.create_table(
        "report_source",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("report_id", sa.String(length=36), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("source_record_id", sa.String(length=36), nullable=False),
        sa.Column("origin_kind", sa.String(length=24), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=True),
        sa.Column("document_revision_id", sa.String(length=36), nullable=True),
        sa.Column("rule_execution_id", sa.String(length=36), nullable=True),
        sa.Column("included_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "origin_kind IN ('medical_document', 'patient_manual', "
            "'system_record', 'rule_execution')",
            name=op.f("ck_report_source_report_source_origin_kind"),
        ),
        sa.CheckConstraint(
            "(origin_kind = 'medical_document' AND document_id IS NOT NULL "
            "AND document_revision_id IS NOT NULL) OR "
            "(origin_kind != 'medical_document' AND document_id IS NULL "
            "AND document_revision_id IS NULL)",
            name=op.f("ck_report_source_report_source_document_identity"),
        ),
        sa.CheckConstraint(
            "(origin_kind = 'rule_execution' AND rule_execution_id IS NOT NULL) OR "
            "(origin_kind != 'rule_execution' AND rule_execution_id IS NULL)",
            name=op.f("ck_report_source_report_source_rule_identity"),
        ),
        sa.CheckConstraint(
            "source_type IN ('patient_profile', 'patient_note', 'medication', "
            "'medication_event', 'medication_daily', 'menstrual_cycle', "
            "'weight_record', 'lab_observation', 'medical_order', "
            "'imaging_report', 'outpatient_record', 'rule_execution')",
            name=op.f("ck_report_source_report_source_type"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.id"],
            name=op.f("fk_report_source_document_id_document"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["document_revision_id"],
            ["document_revision.id"],
            name=op.f("fk_report_source_document_revision_id_document_revision"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["report_snapshot.id"],
            name=op.f("fk_report_source_report_id_report_snapshot"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_source")),
        sa.UniqueConstraint(
            "report_id", "source_type", "source_record_id", name="uq_report_source_record"
        ),
    )
    with op.batch_alter_table("report_source", schema=None) as batch_op:
        batch_op.create_index(
            "ix_report_source_document_revision",
            ["document_id", "document_revision_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("report_source", schema=None) as batch_op:
        batch_op.drop_index("ix_report_source_document_revision")

    op.drop_table("report_source")
    with op.batch_alter_table("report_snapshot", schema=None) as batch_op:
        batch_op.drop_index("ix_report_snapshot_patient_generated")

    op.drop_table("report_snapshot")
    with op.batch_alter_table("patient_note", schema=None) as batch_op:
        batch_op.drop_index("ix_patient_note_patient_created")

    op.drop_table("patient_note")
    # ### end Alembic commands ###
