"""add patient profile fields

Revision ID: 20260827_0013
Revises: 20260827_0012
Create Date: 2026-08-27 19:54:21.809831
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import pomi_backend.db.types

revision: str = "20260827_0013"
down_revision: str | None = "20260827_0012"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("patient_profile", schema=None) as batch_op:
        batch_op.add_column(sa.Column("nickname", sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column("birth_date", sa.Date(), nullable=True))
        batch_op.add_column(sa.Column("gender", sa.String(length=24), nullable=True))
        batch_op.add_column(sa.Column("height_cm", sa.Numeric(precision=4, scale=1), nullable=True))
        batch_op.add_column(sa.Column("diagnosis_year", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("primary_condition", sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column("next_visit_date", sa.Date(), nullable=True))
        batch_op.add_column(sa.Column("health_goal", sa.String(length=500), nullable=True))
        batch_op.add_column(
            sa.Column(
                "onboarding_completed",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )
        batch_op.add_column(
            sa.Column(
                "onboarding_completed_at",
                pomi_backend.db.types.UTCDateTime(timezone=True),
                nullable=True,
            )
        )
        batch_op.create_check_constraint(
            batch_op.f("ck_patient_profile_patient_profile_gender"),
            "gender IS NULL OR gender IN ('female', 'male', 'other', 'prefer_not_to_say')",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("patient_profile", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("ck_patient_profile_patient_profile_gender"), type_="check"
        )
        batch_op.drop_column("onboarding_completed_at")
        batch_op.drop_column("onboarding_completed")
        batch_op.drop_column("health_goal")
        batch_op.drop_column("next_visit_date")
        batch_op.drop_column("primary_condition")
        batch_op.drop_column("diagnosis_year")
        batch_op.drop_column("height_cm")
        batch_op.drop_column("gender")
        batch_op.drop_column("birth_date")
        batch_op.drop_column("nickname")

    # ### end Alembic commands ###
