"""create reconciliation and report tables

Revision ID: 20260827_0004
Revises: 20260827_0003
Create Date: 2026-08-27 18:55:40.728009
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import pomi_backend.db.types

revision: str = "20260827_0004"
down_revision: str | None = "20260827_0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deterministic_rule",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("rule_key", sa.String(length=100), nullable=False),
        sa.Column("rule_type", sa.String(length=32), nullable=False),
        sa.Column("rule_name", sa.String(length=200), nullable=False),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("updated_by_uid", sa.String(length=36), nullable=True),
        sa.Column("updated_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deterministic_rule")),
        sa.UniqueConstraint("rule_key", name=op.f("uq_deterministic_rule_rule_key")),
    )
    op.create_table(
        "patient_note",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("original_text", sa.Text(), nullable=False),
        sa.Column("confirmed_text", sa.Text(), nullable=True),
        sa.Column("confirmation_status", sa.String(length=16), nullable=False),
        sa.Column("confirmed_by_uid", sa.String(length=36), nullable=True),
        sa.Column("confirmed_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("created_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "confirmation_status IN ('draft', 'confirmed', 'cancelled')",
            name=op.f("ck_patient_note_patient_note_status"),
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient_profile.patient_id"],
            name=op.f("fk_patient_note_patient_id_patient_profile"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_patient_note")),
    )
    with op.batch_alter_table("patient_note", schema=None) as batch_op:
        batch_op.create_index(
            "ix_patient_note_patient_created", ["patient_id", "created_at"], unique=False
        )

    op.create_table(
        "rule_execution",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("rule_id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("source_type", sa.String(length=64), nullable=False),
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column("input_digest", sa.String(length=64), nullable=False),
        sa.Column("input", sa.JSON(), nullable=False),
        sa.Column("output", sa.JSON(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("executed_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient_profile.patient_id"],
            name=op.f("fk_rule_execution_patient_id_patient_profile"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["rule_id"],
            ["deterministic_rule.id"],
            name=op.f("fk_rule_execution_rule_id_deterministic_rule"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rule_execution")),
    )
    op.create_table(
        "report_snapshot",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("patient_note_id", sa.String(length=36), nullable=True),
        sa.Column("previous_report_id", sa.String(length=36), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("data_freshness", sa.JSON(), nullable=False),
        sa.Column("source_digest", sa.String(length=64), nullable=False),
        sa.Column("snapshot_hash", sa.String(length=64), nullable=False),
        sa.Column("include_sections", sa.JSON(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("generated_by_uid", sa.String(length=36), nullable=False),
        sa.Column("generated_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("failure_reason", sa.String(length=500), nullable=True),
        sa.CheckConstraint(
            "status IN ('generating', 'succeeded', 'failed')",
            name=op.f("ck_report_snapshot_report_snapshot_status"),
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient_profile.patient_id"],
            name=op.f("fk_report_snapshot_patient_id_patient_profile"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["patient_note_id"],
            ["patient_note.id"],
            name=op.f("fk_report_snapshot_patient_note_id_patient_note"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["previous_report_id"],
            ["report_snapshot.id"],
            name=op.f("fk_report_snapshot_previous_report_id_report_snapshot"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_snapshot")),
        sa.UniqueConstraint("generated_by_uid", "idempotency_key", name="uq_report_idempotency"),
    )
    with op.batch_alter_table("report_snapshot", schema=None) as batch_op:
        batch_op.create_index(
            "ix_report_snapshot_patient_generated", ["patient_id", "generated_at"], unique=False
        )

    op.create_table(
        "medication_reconciliation",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("source_document_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("summary", sa.JSON(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("created_by_uid", sa.String(length=36), nullable=False),
        sa.Column("created_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("confirmed_by_uid", sa.String(length=36), nullable=True),
        sa.Column("confirmed_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'confirmed', 'cancelled')",
            name=op.f("ck_medication_reconciliation_medication_reconciliation_status"),
        ),
        sa.ForeignKeyConstraint(
            ["confirmed_by_uid"],
            ["user_account.uid"],
            name=op.f("fk_medication_reconciliation_confirmed_by_uid_user_account"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_uid"],
            ["user_account.uid"],
            name=op.f("fk_medication_reconciliation_created_by_uid_user_account"),
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient_profile.patient_id"],
            name=op.f("fk_medication_reconciliation_patient_id_patient_profile"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["document.id"],
            name=op.f("fk_medication_reconciliation_source_document_id_document"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_medication_reconciliation")),
        sa.UniqueConstraint(
            "created_by_uid", "idempotency_key", name="uq_reconciliation_idempotency"
        ),
    )
    op.create_table(
        "report_file",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("report_id", sa.String(length=36), nullable=False),
        sa.Column("file_type", sa.String(length=16), nullable=False),
        sa.Column("storage_path", sa.String(length=500), nullable=True),
        sa.Column("file_hash", sa.String(length=64), nullable=True),
        sa.Column("file_size_bytes", sa.Integer(), nullable=True),
        sa.Column("generation_status", sa.String(length=16), nullable=False),
        sa.Column("generated_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("failure_reason", sa.String(length=500), nullable=True),
        sa.CheckConstraint(
            "generation_status IN ('pending', 'processing', 'succeeded', 'failed')",
            name=op.f("ck_report_file_report_file_status"),
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["report_snapshot.id"],
            name=op.f("fk_report_file_report_id_report_snapshot"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_file")),
        sa.UniqueConstraint("report_id", "file_type", name="uq_report_file_type"),
    )
    op.create_table(
        "report_source",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("report_id", sa.String(length=36), nullable=False),
        sa.Column("source_number", sa.Integer(), nullable=False),
        sa.Column("source_type", sa.String(length=64), nullable=False),
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=True),
        sa.Column("document_revision_id", sa.String(length=36), nullable=True),
        sa.Column("rule_execution_id", sa.String(length=36), nullable=True),
        sa.Column("original_value", sa.Text(), nullable=True),
        sa.Column("original_unit", sa.String(length=50), nullable=True),
        sa.Column("reference_range_text", sa.String(length=200), nullable=True),
        sa.Column("material_date", sa.Date(), nullable=True),
        sa.Column("date_source", sa.String(length=50), nullable=False),
        sa.Column("included_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["report_snapshot.id"],
            name=op.f("fk_report_source_report_id_report_snapshot"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_source")),
    )
    op.create_table(
        "medication_reconciliation_item",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("reconciliation_id", sa.String(length=36), nullable=False),
        sa.Column("existing_medication_id", sa.String(length=36), nullable=True),
        sa.Column("new_medical_order_id", sa.String(length=36), nullable=True),
        sa.Column("medication_concept_id", sa.String(length=100), nullable=True),
        sa.Column("drug_name", sa.String(length=200), nullable=False),
        sa.Column("comparison_type", sa.String(length=32), nullable=False),
        sa.Column("rule_id", sa.String(length=36), nullable=True),
        sa.Column("old_instruction", sa.JSON(), nullable=True),
        sa.Column("new_instruction", sa.JSON(), nullable=True),
        sa.Column("differences", sa.JSON(), nullable=False),
        sa.Column("user_decision", sa.String(length=32), nullable=True),
        sa.Column("decision_note", sa.String(length=500), nullable=True),
        sa.Column("stop_date", sa.Date(), nullable=True),
        sa.Column("stop_source", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["existing_medication_id"],
            ["medication.id"],
            name=op.f("fk_medication_reconciliation_item_existing_medication_id_medication"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["new_medical_order_id"],
            ["medical_order.id"],
            name=op.f("fk_medication_reconciliation_item_new_medical_order_id_medical_order"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["reconciliation_id"],
            ["medication_reconciliation.id"],
            name=op.f(
                "fk_medication_reconciliation_item_reconciliation_id_medication_reconciliation"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_medication_reconciliation_item")),
    )
    if op.get_bind().dialect.name == "sqlite":
        op.execute(
            """
            CREATE TRIGGER prevent_report_snapshot_update
            BEFORE UPDATE ON report_snapshot
            BEGIN
                SELECT RAISE(ABORT, 'report snapshots are immutable');
            END
            """
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == "sqlite":
        op.execute("DROP TRIGGER IF EXISTS prevent_report_snapshot_update")
    op.drop_table("medication_reconciliation_item")
    op.drop_table("report_source")
    op.drop_table("report_file")
    op.drop_table("medication_reconciliation")
    with op.batch_alter_table("report_snapshot", schema=None) as batch_op:
        batch_op.drop_index("ix_report_snapshot_patient_generated")

    op.drop_table("report_snapshot")
    op.drop_table("rule_execution")
    with op.batch_alter_table("patient_note", schema=None) as batch_op:
        batch_op.drop_index("ix_patient_note_patient_created")

    op.drop_table("patient_note")
    op.drop_table("deterministic_rule")
    # ### end Alembic commands ###
