"""create document and OCR tables

Revision ID: 20260827_0003
Revises: 20260827_0002
Create Date: 2026-08-27 18:47:32.164229
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import pomi_backend.db.types

revision: str = "20260827_0003"
down_revision: str | None = "20260827_0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "encounter",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("hospital_name", sa.String(length=200), nullable=True),
        sa.Column("department_name", sa.String(length=200), nullable=True),
        sa.Column("doctor_name", sa.String(length=100), nullable=True),
        sa.Column("visit_date", sa.Date(), nullable=True),
        sa.Column("encounter_type", sa.String(length=50), nullable=True),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("created_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient_profile.patient_id"],
            name=op.f("fk_encounter_patient_id_patient_profile"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_encounter")),
    )
    op.create_table(
        "document",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("encounter_id", sa.String(length=36), nullable=True),
        sa.Column("document_type", sa.String(length=32), nullable=False),
        sa.Column("original_file_name", sa.String(length=255), nullable=False),
        sa.Column("mime_type", sa.String(length=64), nullable=False),
        sa.Column("file_size_bytes", sa.Integer(), nullable=False),
        sa.Column("pixel_count", sa.Integer(), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=False),
        sa.Column("file_hash", sa.String(length=64), nullable=False),
        sa.Column("upload_status", sa.String(length=16), nullable=False),
        sa.Column("current_revision_id", sa.String(length=36), nullable=False),
        sa.Column("uploaded_by_uid", sa.String(length=36), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("uploaded_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("purge_after", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "document_type IN ('lab_report', 'medical_order', "
            "'imaging_text_report', 'outpatient_record')",
            name=op.f("ck_document_document_type"),
        ),
        sa.CheckConstraint(
            "upload_status IN ('uploaded', 'processing', 'ready', 'failed', 'deleted')",
            name=op.f("ck_document_document_upload_status"),
        ),
        sa.ForeignKeyConstraint(
            ["encounter_id"],
            ["encounter.id"],
            name=op.f("fk_document_encounter_id_encounter"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient_profile.patient_id"],
            name=op.f("fk_document_patient_id_patient_profile"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_uid"],
            ["user_account.uid"],
            name=op.f("fk_document_uploaded_by_uid_user_account"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document")),
        sa.UniqueConstraint(
            "uploaded_by_uid", "idempotency_key", name="uq_document_upload_idempotency"
        ),
    )
    with op.batch_alter_table("document", schema=None) as batch_op:
        batch_op.create_index(
            "ix_document_patient_type_uploaded",
            ["patient_id", "document_type", "uploaded_at"],
            unique=False,
        )

    op.create_table(
        "document_revision",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("revision_number", sa.Integer(), nullable=False),
        sa.Column("storage_path", sa.String(length=500), nullable=False),
        sa.Column("file_hash", sa.String(length=64), nullable=False),
        sa.Column("file_size_bytes", sa.Integer(), nullable=False),
        sa.Column("replaced_revision_id", sa.String(length=36), nullable=True),
        sa.Column("replacement_reason", sa.String(length=500), nullable=True),
        sa.Column("idempotency_key", sa.String(length=128), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("created_by_uid", sa.String(length=36), nullable=False),
        sa.Column("created_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_uid"],
            ["user_account.uid"],
            name=op.f("fk_document_revision_created_by_uid_user_account"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.id"],
            name=op.f("fk_document_revision_document_id_document"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["replaced_revision_id"],
            ["document_revision.id"],
            name=op.f("fk_document_revision_replaced_revision_id_document_revision"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_revision")),
        sa.UniqueConstraint(
            "document_id", "idempotency_key", name="uq_document_revision_idempotency"
        ),
        sa.UniqueConstraint("document_id", "revision_number", name="uq_document_revision_number"),
    )
    op.create_table(
        "ocr_task",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("document_revision_id", sa.String(length=36), nullable=False),
        sa.Column("document_type", sa.String(length=32), nullable=False),
        sa.Column("task_status", sa.String(length=16), nullable=False),
        sa.Column("model_name", sa.String(length=100), nullable=False),
        sa.Column("prompt_key", sa.String(length=100), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("lease_owner", sa.String(length=200), nullable=True),
        sa.Column(
            "lease_expires_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=True
        ),
        sa.Column("queued_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("started_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("finished_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("processing_ms", sa.Integer(), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.String(length=500), nullable=True),
        sa.Column("result_source", sa.String(length=32), nullable=True),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("created_by_uid", sa.String(length=36), nullable=False),
        sa.CheckConstraint(
            "task_status IN ('pending', 'processing', 'succeeded', 'failed', "
            "'timeout', 'fallback', 'confirmed')",
            name=op.f("ck_ocr_task_ocr_task_status"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_uid"],
            ["user_account.uid"],
            name=op.f("fk_ocr_task_created_by_uid_user_account"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.id"],
            name=op.f("fk_ocr_task_document_id_document"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["document_revision_id"],
            ["document_revision.id"],
            name=op.f("fk_ocr_task_document_revision_id_document_revision"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient_profile.patient_id"],
            name=op.f("fk_ocr_task_patient_id_patient_profile"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ocr_task")),
        sa.UniqueConstraint("created_by_uid", "idempotency_key", name="uq_ocr_task_idempotency"),
    )
    with op.batch_alter_table("ocr_task", schema=None) as batch_op:
        batch_op.create_index("ix_ocr_task_queue", ["task_status", "queued_at"], unique=False)

    op.create_table(
        "ocr_result",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("ocr_task_id", sa.String(length=36), nullable=False),
        sa.Column("raw_response_json", sa.JSON(), nullable=False),
        sa.Column("parsed_result_json", sa.JSON(), nullable=False),
        sa.Column("validation_status", sa.String(length=32), nullable=False),
        sa.Column("validation_errors_json", sa.JSON(), nullable=False),
        sa.Column("confirmed_result_json", sa.JSON(), nullable=True),
        sa.Column("confirmed_by_uid", sa.String(length=36), nullable=True),
        sa.Column("confirmed_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("critical_error", sa.Boolean(), nullable=False),
        sa.Column("created_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["confirmed_by_uid"],
            ["user_account.uid"],
            name=op.f("fk_ocr_result_confirmed_by_uid_user_account"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["ocr_task_id"],
            ["ocr_task.id"],
            name=op.f("fk_ocr_result_ocr_task_id_ocr_task"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ocr_result")),
        sa.UniqueConstraint("ocr_task_id", name=op.f("uq_ocr_result_ocr_task_id")),
    )
    op.create_table(
        "imaging_report",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("ocr_result_id", sa.String(length=36), nullable=False),
        sa.Column("examination_name", sa.String(length=200), nullable=True),
        sa.Column("body_part", sa.String(length=200), nullable=True),
        sa.Column("examination_method", sa.String(length=200), nullable=True),
        sa.Column("findings_text", sa.Text(), nullable=False),
        sa.Column("conclusion_text", sa.Text(), nullable=False),
        sa.Column("examined_at", sa.Date(), nullable=True),
        sa.Column("reported_at", sa.Date(), nullable=True),
        sa.Column("confirmed_by_uid", sa.String(length=36), nullable=False),
        sa.Column("confirmed_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["confirmed_by_uid"],
            ["user_account.uid"],
            name=op.f("fk_imaging_report_confirmed_by_uid_user_account"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.id"],
            name=op.f("fk_imaging_report_document_id_document"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["ocr_result_id"],
            ["ocr_result.id"],
            name=op.f("fk_imaging_report_ocr_result_id_ocr_result"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient_profile.patient_id"],
            name=op.f("fk_imaging_report_patient_id_patient_profile"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_imaging_report")),
    )
    op.create_table(
        "lab_observation",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("ocr_result_id", sa.String(length=36), nullable=False),
        sa.Column("item_name", sa.String(length=200), nullable=False),
        sa.Column("item_code", sa.String(length=100), nullable=True),
        sa.Column("raw_value", sa.String(length=200), nullable=False),
        sa.Column("numeric_value", sa.Float(), nullable=True),
        sa.Column("raw_unit", sa.String(length=50), nullable=True),
        sa.Column("normalized_unit", sa.String(length=50), nullable=True),
        sa.Column("reference_range_text", sa.String(length=200), nullable=True),
        sa.Column("reference_low", sa.Float(), nullable=True),
        sa.Column("reference_high", sa.Float(), nullable=True),
        sa.Column("abnormal_status", sa.String(length=16), nullable=True),
        sa.Column("sample_date", sa.Date(), nullable=True),
        sa.Column("report_date", sa.Date(), nullable=True),
        sa.Column("confirmed_by_uid", sa.String(length=36), nullable=False),
        sa.Column("confirmed_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["confirmed_by_uid"],
            ["user_account.uid"],
            name=op.f("fk_lab_observation_confirmed_by_uid_user_account"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.id"],
            name=op.f("fk_lab_observation_document_id_document"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["ocr_result_id"],
            ["ocr_result.id"],
            name=op.f("fk_lab_observation_ocr_result_id_ocr_result"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient_profile.patient_id"],
            name=op.f("fk_lab_observation_patient_id_patient_profile"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lab_observation")),
    )
    op.create_table(
        "medical_order",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("ocr_result_id", sa.String(length=36), nullable=False),
        sa.Column("source_text", sa.Text(), nullable=False),
        sa.Column("drug_name", sa.String(length=200), nullable=False),
        sa.Column("normalized_drug_name", sa.String(length=200), nullable=False),
        sa.Column("specification", sa.String(length=200), nullable=True),
        sa.Column("dosage_text", sa.String(length=300), nullable=True),
        sa.Column("dosage_value", sa.Float(), nullable=True),
        sa.Column("dosage_unit", sa.String(length=50), nullable=True),
        sa.Column("frequency", sa.String(length=100), nullable=True),
        sa.Column("duration", sa.String(length=100), nullable=True),
        sa.Column("route", sa.String(length=100), nullable=True),
        sa.Column("instruction", sa.Text(), nullable=True),
        sa.Column("prescribed_at", sa.Date(), nullable=True),
        sa.Column("confirmed_by_uid", sa.String(length=36), nullable=False),
        sa.Column("confirmed_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["confirmed_by_uid"],
            ["user_account.uid"],
            name=op.f("fk_medical_order_confirmed_by_uid_user_account"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.id"],
            name=op.f("fk_medical_order_document_id_document"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["ocr_result_id"],
            ["ocr_result.id"],
            name=op.f("fk_medical_order_ocr_result_id_ocr_result"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient_profile.patient_id"],
            name=op.f("fk_medical_order_patient_id_patient_profile"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_medical_order")),
    )
    op.create_table(
        "ocr_field_result",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("ocr_result_id", sa.String(length=36), nullable=False),
        sa.Column("field_path", sa.String(length=500), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=True),
        sa.Column("parsed_value", sa.JSON(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("uncertainty_reason", sa.String(length=500), nullable=True),
        sa.Column("source_region", sa.JSON(), nullable=True),
        sa.Column("user_value", sa.JSON(), nullable=True),
        sa.Column("confirmation_status", sa.String(length=24), nullable=False),
        sa.Column("confirmed_by_uid", sa.String(length=36), nullable=True),
        sa.Column("confirmed_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["confirmed_by_uid"],
            ["user_account.uid"],
            name=op.f("fk_ocr_field_result_confirmed_by_uid_user_account"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["ocr_result_id"],
            ["ocr_result.id"],
            name=op.f("fk_ocr_field_result_ocr_result_id_ocr_result"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ocr_field_result")),
        sa.UniqueConstraint("ocr_result_id", "field_path", name="uq_ocr_field_result_path"),
    )
    op.create_table(
        "outpatient_record",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("ocr_result_id", sa.String(length=36), nullable=False),
        sa.Column("hospital_name", sa.String(length=200), nullable=True),
        sa.Column("department_name", sa.String(length=200), nullable=True),
        sa.Column("doctor_name", sa.String(length=100), nullable=True),
        sa.Column("visit_date", sa.Date(), nullable=False),
        sa.Column("chief_complaint", sa.Text(), nullable=False),
        sa.Column("diagnosis_summary", sa.Text(), nullable=False),
        sa.Column("treatment_plan", sa.Text(), nullable=True),
        sa.Column("medical_advice", sa.Text(), nullable=True),
        sa.Column("confirmed_by_uid", sa.String(length=36), nullable=False),
        sa.Column("confirmed_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["confirmed_by_uid"],
            ["user_account.uid"],
            name=op.f("fk_outpatient_record_confirmed_by_uid_user_account"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.id"],
            name=op.f("fk_outpatient_record_document_id_document"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["ocr_result_id"],
            ["ocr_result.id"],
            name=op.f("fk_outpatient_record_ocr_result_id_ocr_result"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient_profile.patient_id"],
            name=op.f("fk_outpatient_record_patient_id_patient_profile"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outpatient_record")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("outpatient_record")
    op.drop_table("ocr_field_result")
    op.drop_table("medical_order")
    op.drop_table("lab_observation")
    op.drop_table("imaging_report")
    op.drop_table("ocr_result")
    with op.batch_alter_table("ocr_task", schema=None) as batch_op:
        batch_op.drop_index("ix_ocr_task_queue")

    op.drop_table("ocr_task")
    op.drop_table("document_revision")
    with op.batch_alter_table("document", schema=None) as batch_op:
        batch_op.drop_index("ix_document_patient_type_uploaded")

    op.drop_table("document")
    op.drop_table("encounter")
    # ### end Alembic commands ###
