"""add OCR task worker pipeline

Revision ID: 20260827_0028
Revises: 20260827_0027
Create Date: 2026-08-27 20:54:17.468719
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import pomi_backend.db.types

revision: str = "20260827_0028"
down_revision: str | None = "20260827_0027"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ocr_task",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("requested_by_uid", sa.String(length=36), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("document_revision_id", sa.String(length=36), nullable=False),
        sa.Column("material_type", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("model_name", sa.String(length=100), nullable=False),
        sa.Column("prompt_version", sa.String(length=40), nullable=False),
        sa.Column("schema_version", sa.String(length=40), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("parent_task_id", sa.String(length=36), nullable=True),
        sa.Column("provider_attempts", sa.Integer(), nullable=False),
        sa.Column("attempt_history", sa.JSON(), nullable=False),
        sa.Column("lease_owner", sa.String(length=100), nullable=True),
        sa.Column(
            "lease_expires_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=True
        ),
        sa.Column("available_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column(
            "provider_call_started_at",
            pomi_backend.db.types.UTCDateTime(timezone=True),
            nullable=True,
        ),
        sa.Column("started_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("finished_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("error_category", sa.String(length=40), nullable=True),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("error_message", sa.String(length=500), nullable=True),
        sa.Column("result_source", sa.String(length=80), nullable=True),
        sa.Column("deduplication_key", sa.String(length=64), nullable=False),
        sa.Column("created_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "material_type IN ('lab_report', 'medical_order', "
            "'imaging_text_report', 'outpatient_record')",
            name=op.f("ck_ocr_task_ocr_task_material_type"),
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'processing', 'pending_confirmation', "
            "'confirmed', 'failed', 'timed_out')",
            name=op.f("ck_ocr_task_ocr_task_status"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.id"],
            name=op.f("fk_ocr_task_document_id_document"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["document_revision_id"],
            ["document_revision.id"],
            name=op.f("fk_ocr_task_document_revision_id_document_revision"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["parent_task_id"],
            ["ocr_task.id"],
            name=op.f("fk_ocr_task_parent_task_id_ocr_task"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient_profile.patient_id"],
            name=op.f("fk_ocr_task_patient_id_patient_profile"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_uid"],
            ["user_account.uid"],
            name=op.f("fk_ocr_task_requested_by_uid_user_account"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ocr_task")),
        sa.UniqueConstraint("deduplication_key", name="uq_ocr_task_deduplication_key"),
        sa.UniqueConstraint("parent_task_id", name="uq_ocr_task_parent_retry"),
    )
    with op.batch_alter_table("ocr_task", schema=None) as batch_op:
        batch_op.create_index(
            "ix_ocr_task_claim", ["status", "available_at", "lease_expires_at"], unique=False
        )
        batch_op.create_index(
            "ix_ocr_task_patient_created", ["patient_id", "created_at"], unique=False
        )

    op.create_table(
        "ocr_result",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("raw_response", sa.JSON(), nullable=False),
        sa.Column("validated_draft", sa.JSON(), nullable=False),
        sa.Column("user_modified_data", sa.JSON(), nullable=True),
        sa.Column("confirmed_data", sa.JSON(), nullable=True),
        sa.Column("created_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["ocr_task.id"],
            name=op.f("fk_ocr_result_task_id_ocr_task"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ocr_result")),
        sa.UniqueConstraint("task_id", name=op.f("uq_ocr_result_task_id")),
    )
    op.create_table(
        "ocr_field_result",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("result_id", sa.String(length=36), nullable=False),
        sa.Column("field_path", sa.String(length=300), nullable=False),
        sa.Column("source_text", sa.Text(), nullable=True),
        sa.Column("parsed_value", sa.JSON(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("uncertainty_reason", sa.String(length=500), nullable=True),
        sa.Column("source_region", sa.JSON(), nullable=True),
        sa.Column("user_value", sa.JSON(), nullable=True),
        sa.Column("confirmation_status", sa.String(length=16), nullable=False),
        sa.Column("created_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "confirmation_status IN ('pending', 'accepted', 'corrected', 'rejected')",
            name=op.f("ck_ocr_field_result_ocr_field_confirmation_status"),
        ),
        sa.ForeignKeyConstraint(
            ["result_id"],
            ["ocr_result.id"],
            name=op.f("fk_ocr_field_result_result_id_ocr_result"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ocr_field_result")),
        sa.UniqueConstraint("result_id", "field_path", name="uq_ocr_field_result_path"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ocr_field_result")
    op.drop_table("ocr_result")
    with op.batch_alter_table("ocr_task", schema=None) as batch_op:
        batch_op.drop_index("ix_ocr_task_patient_created")
        batch_op.drop_index("ix_ocr_task_claim")

    op.drop_table("ocr_task")
    # ### end Alembic commands ###
