"""create private document revisions

Revision ID: 20260827_0020
Revises: 20260827_0015
Create Date: 2026-08-27 20:15:10.710614
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import pomi_backend.db.types

revision: str = "20260827_0020"
down_revision: str | None = "20260827_0015"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("document_type", sa.String(length=32), nullable=False),
        sa.Column("original_file_name", sa.String(length=255), nullable=False),
        sa.Column("mime_type", sa.String(length=64), nullable=False),
        sa.Column("file_size_bytes", sa.Integer(), nullable=False),
        sa.Column("pixel_count", sa.Integer(), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=False),
        sa.Column("file_hash", sa.String(length=64), nullable=False),
        sa.Column("current_revision_id", sa.String(length=36), nullable=False),
        sa.Column("upload_status", sa.String(length=16), nullable=False),
        sa.Column("uploaded_by_uid", sa.String(length=36), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("processing_notice_version", sa.String(length=40), nullable=True),
        sa.Column(
            "processing_notice_accepted_at",
            pomi_backend.db.types.UTCDateTime(timezone=True),
            nullable=True,
        ),
        sa.Column("uploaded_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("purge_after", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "document_type IN ('lab_report', 'medical_order', "
            "'imaging_text_report', 'outpatient_record')",
            name=op.f("ck_document_document_type"),
        ),
        sa.CheckConstraint(
            "upload_status IN ('uploaded', 'ready', 'failed', 'deleted')",
            name=op.f("ck_document_document_upload_status"),
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient_profile.patient_id"],
            name=op.f("fk_document_patient_id_patient_profile"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_uid"],
            ["user_account.uid"],
            name=op.f("fk_document_uploaded_by_uid_user_account"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document")),
        sa.UniqueConstraint(
            "uploaded_by_uid", "idempotency_key", name="uq_document_upload_idempotency"
        ),
    )
    with op.batch_alter_table("document", schema=None) as batch_op:
        batch_op.create_index(
            "ix_document_patient_uploaded", ["patient_id", "uploaded_at"], unique=False
        )

    op.create_table(
        "document_revision",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("revision_number", sa.Integer(), nullable=False),
        sa.Column("storage_path", sa.String(length=500), nullable=False),
        sa.Column("file_hash", sa.String(length=64), nullable=False),
        sa.Column("file_size_bytes", sa.Integer(), nullable=False),
        sa.Column("mime_type", sa.String(length=64), nullable=False),
        sa.Column("pixel_count", sa.Integer(), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=False),
        sa.Column("replaced_revision_id", sa.String(length=36), nullable=True),
        sa.Column("replacement_reason", sa.String(length=500), nullable=True),
        sa.Column("idempotency_key", sa.String(length=128), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("created_by_uid", sa.String(length=36), nullable=False),
        sa.Column("created_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_uid"],
            ["user_account.uid"],
            name=op.f("fk_document_revision_created_by_uid_user_account"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.id"],
            name=op.f("fk_document_revision_document_id_document"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["replaced_revision_id"],
            ["document_revision.id"],
            name=op.f("fk_document_revision_replaced_revision_id_document_revision"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_revision")),
        sa.UniqueConstraint(
            "document_id", "idempotency_key", name="uq_document_revision_idempotency"
        ),
        sa.UniqueConstraint("document_id", "revision_number", name="uq_document_revision_number"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("document_revision")
    with op.batch_alter_table("document", schema=None) as batch_op:
        batch_op.drop_index("ix_document_patient_uploaded")

    op.drop_table("document")
    # ### end Alembic commands ###
