"""add confirmed lab observations

Revision ID: 20260827_0022_lab
Revises: 20260827_0021
Create Date: 2026-08-27 21:15:00.322585
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import pomi_backend.db.types

revision: str = "20260827_0022_lab"
down_revision: str | None = "20260827_0021"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lab_observation",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("visit_id", sa.String(length=100), nullable=True),
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("document_revision_id", sa.String(length=36), nullable=False),
        sa.Column("ocr_result_id", sa.String(length=36), nullable=False),
        sa.Column("item_index", sa.Integer(), nullable=False),
        sa.Column("original_item_name", sa.String(length=200), nullable=False),
        sa.Column("standard_metric_id", sa.String(length=80), nullable=True),
        sa.Column("mapping_status", sa.String(length=24), nullable=False),
        sa.Column("raw_value", sa.String(length=100), nullable=False),
        sa.Column("numeric_value", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("original_unit", sa.String(length=40), nullable=False),
        sa.Column("standard_unit", sa.String(length=40), nullable=False),
        sa.Column("reference_range_raw", sa.String(length=120), nullable=True),
        sa.Column("reference_lower", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("reference_upper", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("abnormal_status", sa.String(length=16), nullable=False),
        sa.Column("sample_date", sa.Date(), nullable=True),
        sa.Column("exam_date", sa.Date(), nullable=True),
        sa.Column("report_date", sa.Date(), nullable=True),
        sa.Column("visit_date", sa.Date(), nullable=True),
        sa.Column("trend_date", sa.Date(), nullable=True),
        sa.Column("trend_date_source", sa.String(length=20), nullable=True),
        sa.Column("original_item_data", sa.JSON(), nullable=False),
        sa.Column("confirmed_item_data", sa.JSON(), nullable=False),
        sa.Column("confirmed_by_uid", sa.String(length=36), nullable=False),
        sa.Column("confirmed_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "abnormal_status IN ('low', 'normal', 'high', 'unknown')",
            name=op.f("ck_lab_observation_lab_observation_abnormal_status"),
        ),
        sa.CheckConstraint(
            "mapping_status IN ('mapped', 'needs_manual_review')",
            name=op.f("ck_lab_observation_lab_observation_mapping_status"),
        ),
        sa.CheckConstraint(
            "trend_date_source IS NULL OR trend_date_source IN "
            "('sample_date', 'exam_date', 'report_date', 'visit_date')",
            name=op.f("ck_lab_observation_lab_observation_trend_date_source"),
        ),
        sa.ForeignKeyConstraint(
            ["confirmed_by_uid"],
            ["user_account.uid"],
            name=op.f("fk_lab_observation_confirmed_by_uid_user_account"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.id"],
            name=op.f("fk_lab_observation_document_id_document"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["document_revision_id"],
            ["document_revision.id"],
            name=op.f("fk_lab_observation_document_revision_id_document_revision"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["ocr_result_id"],
            ["ocr_result.id"],
            name=op.f("fk_lab_observation_ocr_result_id_ocr_result"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient_profile.patient_id"],
            name=op.f("fk_lab_observation_patient_id_patient_profile"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lab_observation")),
        sa.UniqueConstraint("ocr_result_id", "item_index", name="uq_lab_observation_result_item"),
    )
    with op.batch_alter_table("lab_observation", schema=None) as batch_op:
        batch_op.create_index(
            "ix_lab_observation_document_revision",
            ["document_id", "document_revision_id"],
            unique=False,
        )
        batch_op.create_index(
            "ix_lab_observation_patient_metric_date",
            ["patient_id", "standard_metric_id", "trend_date"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lab_observation", schema=None) as batch_op:
        batch_op.drop_index("ix_lab_observation_patient_metric_date")
        batch_op.drop_index("ix_lab_observation_document_revision")

    op.drop_table("lab_observation")
    # ### end Alembic commands ###
