"""create health record foundation

Revision ID: 20260827_0012
Revises: 20260826_0001
Create Date: 2026-08-27 19:41:35.319063
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import pomi_backend.db.types

revision: str = "20260827_0012"
down_revision: str | None = "20260826_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "patient_profile",
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("account_uid", sa.String(length=36), nullable=False),
        sa.Column("created_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_uid"],
            ["user_account.uid"],
            name=op.f("fk_patient_profile_account_uid_user_account"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("patient_id", name=op.f("pk_patient_profile")),
        sa.UniqueConstraint("account_uid", name=op.f("uq_patient_profile_account_uid")),
    )
    op.create_table(
        "medication",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("drug_name", sa.String(length=200), nullable=False),
        sa.Column("source_category", sa.String(length=32), nullable=False),
        sa.Column("specification", sa.String(length=200), nullable=True),
        sa.Column("dosage_value", sa.Numeric(precision=8, scale=3), nullable=True),
        sa.Column("dosage_unit", sa.String(length=32), nullable=True),
        sa.Column("frequency", sa.String(length=200), nullable=True),
        sa.Column("route", sa.String(length=80), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("replaces_medication_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "source_category IN ('prescribed', 'supplement', 'other_long_term')",
            name=op.f("ck_medication_medication_source_category"),
        ),
        sa.CheckConstraint(
            "status IN ('active', 'paused', 'stopped')",
            name=op.f("ck_medication_medication_status"),
        ),
        sa.CheckConstraint(
            "end_date IS NULL OR start_date IS NULL OR end_date >= start_date",
            name=op.f("ck_medication_medication_date_order"),
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient_profile.patient_id"],
            name=op.f("fk_medication_patient_id_patient_profile"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id", "replaces_medication_id"],
            ["medication.patient_id", "medication.id"],
            name="fk_medication_replacement_same_patient",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_medication")),
        sa.UniqueConstraint("patient_id", "id", name="uq_medication_patient_id"),
    )
    with op.batch_alter_table("medication", schema=None) as batch_op:
        batch_op.create_index(
            "ix_medication_patient_status", ["patient_id", "status"], unique=False
        )

    op.create_table(
        "menstrual_cycle",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("deleted_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("created_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "end_date IS NULL OR end_date >= start_date",
            name=op.f("ck_menstrual_cycle_menstrual_cycle_date_order"),
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient_profile.patient_id"],
            name=op.f("fk_menstrual_cycle_patient_id_patient_profile"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_menstrual_cycle")),
    )
    with op.batch_alter_table("menstrual_cycle", schema=None) as batch_op:
        batch_op.create_index(
            "ix_menstrual_cycle_patient_start", ["patient_id", "start_date"], unique=False
        )

    op.create_table(
        "weight_record",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("record_date", sa.Date(), nullable=False),
        sa.Column("weight_kg", sa.Numeric(precision=4, scale=1), nullable=False),
        sa.Column("created_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "weight_kg >= 20 AND weight_kg <= 300", name=op.f("ck_weight_record_weight_range")
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient_profile.patient_id"],
            name=op.f("fk_weight_record_patient_id_patient_profile"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_weight_record")),
        sa.UniqueConstraint("patient_id", "record_date", name="uq_weight_patient_date"),
    )
    with op.batch_alter_table("weight_record", schema=None) as batch_op:
        batch_op.create_index(
            "ix_weight_record_patient_date", ["patient_id", "record_date"], unique=False
        )

    op.create_table(
        "medication_daily",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("medication_id", sa.String(length=36), nullable=False),
        sa.Column("record_date", sa.Date(), nullable=False),
        sa.Column("intake_status", sa.String(length=16), nullable=False),
        sa.Column("recorded_by_uid", sa.String(length=36), nullable=False),
        sa.Column("recorded_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "intake_status IN ('taken', 'missed')",
            name=op.f("ck_medication_daily_medication_daily_status"),
        ),
        sa.ForeignKeyConstraint(
            ["patient_id", "medication_id"],
            ["medication.patient_id", "medication.id"],
            name="fk_medication_daily_medication_same_patient",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient_profile.patient_id"],
            name=op.f("fk_medication_daily_patient_id_patient_profile"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by_uid"],
            ["user_account.uid"],
            name=op.f("fk_medication_daily_recorded_by_uid_user_account"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_medication_daily")),
        sa.UniqueConstraint("medication_id", "record_date", name="uq_medication_daily_date"),
    )
    with op.batch_alter_table("medication_daily", schema=None) as batch_op:
        batch_op.create_index(
            "ix_medication_daily_patient_date", ["patient_id", "record_date"], unique=False
        )

    op.create_table(
        "medication_event",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("medication_id", sa.String(length=36), nullable=False),
        sa.Column("event_type", sa.String(length=16), nullable=False),
        sa.Column("event_date", sa.Date(), nullable=False),
        sa.Column("old_instruction", sa.JSON(), nullable=True),
        sa.Column("new_instruction", sa.JSON(), nullable=True),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("source_document_id", sa.String(length=36), nullable=True),
        sa.Column("acted_by_uid", sa.String(length=36), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", pomi_backend.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "event_type IN ('created', 'adjusted', 'paused', 'resumed', 'stopped')",
            name=op.f("ck_medication_event_medication_event_type"),
        ),
        sa.ForeignKeyConstraint(
            ["acted_by_uid"],
            ["user_account.uid"],
            name=op.f("fk_medication_event_acted_by_uid_user_account"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id", "medication_id"],
            ["medication.patient_id", "medication.id"],
            name="fk_medication_event_medication_same_patient",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient_profile.patient_id"],
            name=op.f("fk_medication_event_patient_id_patient_profile"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_medication_event")),
    )
    with op.batch_alter_table("medication_event", schema=None) as batch_op:
        batch_op.create_index(
            "ix_medication_event_medication_date", ["medication_id", "event_date"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("medication_event", schema=None) as batch_op:
        batch_op.drop_index("ix_medication_event_medication_date")

    op.drop_table("medication_event")
    with op.batch_alter_table("medication_daily", schema=None) as batch_op:
        batch_op.drop_index("ix_medication_daily_patient_date")

    op.drop_table("medication_daily")
    with op.batch_alter_table("weight_record", schema=None) as batch_op:
        batch_op.drop_index("ix_weight_record_patient_date")

    op.drop_table("weight_record")
    with op.batch_alter_table("menstrual_cycle", schema=None) as batch_op:
        batch_op.drop_index("ix_menstrual_cycle_patient_start")

    op.drop_table("menstrual_cycle")
    with op.batch_alter_table("medication", schema=None) as batch_op:
        batch_op.drop_index("ix_medication_patient_status")

    op.drop_table("medication")
    op.drop_table("patient_profile")
    # ### end Alembic commands ###
